import React from 'react';
import { 
  ShieldCheck, 
  Info, 
  CheckCircle2, 
  AlertTriangle, 
  ListTree, 
  ChevronDown, 
  ArrowRight,
  Search,
  User // Added User icon for the profile logo
} from 'lucide-react';
import './TransparencyReport.css';

export default function TransparencyReport({ onBack }) {
  return (
    <div className="report-page">
      {/* Top Navigation Bar */}
      <nav className="report-nav">
        <div className="nav-container">
          <div className="nav-left">
            <div className="nav-logo" onClick={onBack} style={{cursor: 'pointer'}}>
              <div className="nav-logo-box"><div className="nav-logo-inner" /></div>
              <span>SafeFood AI</span>
            </div>
            <div className="nav-links">
              <button className="nav-item">History</button>
              <button className="nav-item">Settings</button>
            </div>
          </div>
          <div className="nav-right">
            <div className="search-box">
              <Search size={18} className="search-icon" />
              <input type="text" placeholder="Search products..." />
            </div>
            {/* Updated Profile Logo Section */}
            <div className="profile-logo-circle">
              <User size={18} color="#18dc6a" />
            </div>
          </div>
        </div>
      </nav>

      <main className="report-content">
        <header className="report-header">
          <span className="section-label">TRANSPARENCY REPORT</span>
          <h1 className="report-title">How we analyzed this product</h1>
          <p className="report-subtitle">
            A complete breakdown of our findings for <strong>Organic Plant-Based Burger Patties</strong>.
          </p>
        </header>

        <div className="report-grid">
          {/* Left Column */}
          <div className="report-main-col">
            <section className="report-card">
              <div className="card-header">
                <ShieldCheck className="icon-green" size={24} />
                <h2>Analysis Conclusion</h2>
              </div>
              <p className="card-text">
                Based on your preferences for <strong>Low Sugar</strong> and <strong>Vegan</strong> diets, we analyzed the nutritional panel and 45 distinct ingredients to ensure they meet your safety standards. The product contains no animal-derived ingredients and falls within the acceptable sugar intake range for a single serving.
              </p>
              <div className="pill-group">
                <span className="pill pill-success">Safe to consume</span>
                <span className="pill pill-default">No Allergens Detected</span>
              </div>
            </section>

            <section className="report-card">
              <div className="card-header">
                <h2>Our Philosophy</h2>
              </div>
              <p className="card-text">
                We focus on ingredients that impact daily health decisions. Our AI prioritizes evidence-based nutritional science over marketing claims. We flag additives, excessive preservatives, and hidden sugars to give you a clear picture of what you are eating.
              </p>
            </section>

            <section className="report-card accordion">
              <div className="accordion-header">
                <div className="header-left">
                  <ListTree className="icon-gray" size={20} />
                  <span>Full Ingredient List (45 items)</span>
                </div>
                <ChevronDown size={20} className="icon-gray" />
              </div>
            </section>
          </div>

          {/* Right Column */}
          <div className="report-side-col">
            <section className="report-card side-card">
              <h3>DATA SOURCES</h3>
              <ul className="source-list">
                <li><CheckCircle2 size={16} className="icon-green" /> USDA FoodData Central</li>
                <li><CheckCircle2 size={16} className="icon-green" /> OpenFoodFacts Database</li>
                <li><CheckCircle2 size={16} className="icon-green" /> FDA GRAS List (Generally Recognized as Safe)</li>
              </ul>
              <button className="link-btn">
                Learn more about our methodology <ArrowRight size={16} />
              </button>
            </section>

            <section className="report-card side-card warning-card">
              <div className="card-header warning">
                <AlertTriangle size={18} />
                <h3>Important Disclaimer</h3>
              </div>
              <p className="warning-text">
                This analysis is generated by AI and is not medical advice. While we strive for accuracy, formulations can change. Always check the physical packaging label before consumption.
              </p>
            </section>
          </div>
        </div>
      </main>

      <footer className="report-footer">
        <div className="footer-container">
          <p>© 2023 SafeFood AI. All rights reserved.</p>
          <div className="footer-links">
            <button>Privacy Policy</button>
            <button>Terms of Service</button>
          </div>
        </div>
      </footer>
    </div>
  );
}